### ISSUE TITLE
Intel MKL FATAL ERROR

### ISSUE THREAD

**Issue by BastienNguyen** [tkonopka/umap#12]
Hi,

The package was working just fine and suddenly now whenever I try to load library(umap) it throws this errors;

`INTEL MKL ERROR: dlopen(/Users/nguyenb/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/nguyenb/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.`

I already try to reinstall reticulate and umap...
Many thanks for your help!

Bastien

**Comment by tkonopka** [comment]
Hi, Sorry, but I'm not sure exactly what this means. Perhaps some things to try

- run library(reticulate) before library(umap). (The package recently had trouble using functions that were meant to be imported but were not available by mistake. Loading the library might help.)

- outside of the R environment, make sure you can run python and import the umap-learn library there. Just executing `import umap` on a python prompt should be enough to tell it is installed correctly. 

- the message text with 'INTEL MKL' gives the impression this is related to python internals. Perhaps the community at reticulate will be more knowledgeable on the issue. 

Sorry not to be of more help here.

**Comment by BastienNguyen** [comment]
Thank you for you reply.
I finally identified the problem. The python version that reticulate pointed was different from my python (python3.7).
So I had to change the .Rprofile and specify `RETICULATE_PYTHON="/usr/local/bin/python3"`.
I hope it will help others.

**Comment by tkonopka** [comment]
Glad you found and shared a solution
