### ISSUE TITLE
transforming new data to an embedding

### ISSUE THREAD

**Issue by sheffe** [tkonopka/umap#3]
Hi Tomasz, thanks for this package! Following [the UMAP docs here](https://umap-learn.readthedocs.io/en/latest/transform.html), one nice advantage over tSNE is the ability to transform new data to an existing embedding for use in feature preprocessing. Do you know if/how this might be done through your `reticulate` wrapper?

**Comment by tkonopka** [comment]
Thanks for the suggestion.

I updated the output of function `umap(d, method="umap-learn")` to include a component `UMAP`. It now contains the python object used to fit the training data. In the short term, you can now use this object for any follow-up. For example:

```
## two subsets of iris
training = iris[seq(1,150,by=2), 1:4]
test     = iris[seq(2,150,by=2), 1:4]

## fit on training data
training_fit = umap(training, method="umap-learn")
layout_training = training_fit$layout

## transform/predict for training and test data
layout_confirm = training_fit$UMAP$transform(training)
layout_test    = training_fit$UMAP$transform(test)

## visualize ...
## layout_training and layout_confirm should be similar (by construction)
## layout_test should have similar structure to layout_training
## (the 'similar' structure may not be obvious on iris data, 
##  but try on larger data, e.g. mnist, and it does work)
```

This is a temporary solution. In the longer term, it would be great to have an R function for the transform that would work with both the "naive" and "umap-learn" methods.

**Comment by sheffe** [comment]
This looks like a complete short-term solution for what I had in mind, thanks! I agree with your design suggestion on a unified transform interface. Ultimately I'd love to see `umap` pulled in as a preprocessing option in the `recipes` library, akin to how you might use `step_pca` or similar, but it's a heavy dependency if everything runs through `reticulate.` I'm going to experiment over the weekend, hopefully.

Thanks again, this was a very fast solution!

**Comment by tkonopka** [comment]
Transformation of new data is now available via function `predict()` and works with both the R and python implementations. The vignette has an example. 

I'll leave linking with `recipes` for another time/ticket. Closing this for now.
