### ISSUE TITLE
Error with n_components=1

### ISSUE THREAD

**Issue by mbosio85** [tkonopka/umap#4]
Hello,
I am trying to use umap in R and wanted to try editing the configuration n_components to 1.
When I do it I get an error : 
```
custom.config = umap.defaults
custom.config$n_components=1
aa.umap = umap(aa, config = custom.config)
Error in result[, 1:d, drop = FALSE] : incorrect number of dimensions
```
Is there a way I can extract a reduction to only 1 component ?

Thanks for the info
Mattia

**Comment by tkonopka** [comment]
Posted an update that fixes the bug (at least with the example with the iris dataset).
