### ISSUE TITLE
Number of threads

### ISSUE THREAD

**Issue by lmweber** [tkonopka/umap#5]
Hi, is it possible to specify the number of threads to use? I have been running umap on our multi-core server, and it seems to simply use all available cores. It would be useful to provide a user argument to specify the number of threads. Thanks!

**Comment by tkonopka** [comment]
Hi. Thanks for trying out the package. 

All the code in the package is implemented for single-core execution, so the server-swamping behavior is surprising. Are you sure this occurs within a single call to umap()?

It would be useful if you could post a small example that shows this behavior. In particular, are you loading any other packages, or running custom code related to parallelization?

**Comment by lmweber** [comment]
Thanks for the reply. I am running umap within a Snakemake pipeline, where I am calling it multiple times with different parameters and random seeds.

I tried to isolate a small example to post here, but found that the problem no longer occurred in the smaller example. So it seems likely that the problem is somewhere in the way I have set up the Snakemake pipeline, and not in umap itself.

If I find out more, I will post here again. But at this point it looks like the problem is probably somewhere in my Snakemake setup. Sorry for the confusion!

**Comment by tkonopka** [comment]
Ok, no worries. I'll close this for now, but we can revisit if something else turns up. 

As an aside: you mentioned testing several configurations and parameters. If you find certain parameters might benefit from different defaults, please do get in touch; that would be quite valuable. There is always the possibility to change the object `umap.defaults`, or to provide additional configuration objects for specific applications, e.g. in bioinformatics.
